name: CI

on:
  - push
  - pull_request

jobs:
  check-scripts:
    runs-on: ubuntu-22.04
    name: Check scripts
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install weechat-script-lint
      - name: Check scripts
        run: make partial-check
